# Generated by Django 2.1.7 on 2019-02-21 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('untBSCore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='untbscore',
            old_name='hourse',
            new_name='hours',
        ),
    ]
