# Generated by Django 2.1.7 on 2019-02-21 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='courses',
            new_name='Course',
        ),
    ]
