# Generated by Django 2.1.7 on 2019-02-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190220_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prereq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.PositiveSmallIntegerField()),
                ('courseDept', models.CharField(max_length=4)),
                ('prereqCourseID', models.PositiveSmallIntegerField()),
                ('prereqCourseDept', models.CharField(max_length=4)),
            ],
        ),
    ]
