# Generated by Django 2.1.7 on 2019-03-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_prereq'),
    ]

    operations = [
        migrations.AddField(
            model_name='prereq',
            name='name',
            field=models.CharField(default='prereq course name', max_length=100),
        ),
    ]
