# Generated by Django 2.1.7 on 2019-03-05 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_prereq_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prereq',
        ),
    ]
