# Generated by Django 2.1.7 on 2019-03-05 23:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_delete_prereq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prereq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.PositiveSmallIntegerField()),
                ('courseDept', models.CharField(max_length=4)),
                ('prereqCourses', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
