# Generated by Django 2.1.7 on 2019-02-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransferCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.PositiveSmallIntegerField(null=True)),
                ('courseDept', models.CharField(max_length=4, null=True)),
                ('name', models.CharField(max_length=50)),
                ('equivalentToID', models.PositiveSmallIntegerField()),
                ('equivalentToDept', models.CharField(max_length=4)),
                ('requiredScore', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
