# Generated by Django 2.1.7 on 2019-04-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferCredits', '0002_auto_20190220_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfercredit',
            name='equivalentToID',
            field=models.CharField(max_length=4),
        ),
    ]
