# Generated by Django 2.1.2 on 2019-04-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190412_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='temp', max_length=50),
        ),
    ]
