# Generated by Django 2.2 on 2019-04-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecmCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techclasses',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
